// Package models Code generated by swaggo/swag. DO NOT EDIT
package models

import "go.mongodb.org/mongo-driver/bson/primitive"

type Stat struct {
	ID        primitive.ObjectID `bson:"_id,omitempty" json:"id" swaggertype:"string"`
	Type      string             `bson:"type" json:"type" binding:"required"`
	Value     float64            `bson:"value" json:"value" binding:"required"`
	Timestamp primitive.DateTime `bson:"timestamp" json:"timestamp" swaggertype:"string"`
}
