// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/chess.proto

package chess

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	Move          string                 `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_chess_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *MoveRequest) GetMove() string {
	if x != nil {
		return x.Move
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLegal       bool                   `protobuf:"varint,1,opt,name=is_legal,json=isLegal,proto3" json:"is_legal,omitempty"`
	NewFen        string                 `protobuf:"bytes,2,opt,name=new_fen,json=newFen,proto3" json:"new_fen,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_chess_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_chess_proto_rawDescGZIP(), []int{1}
}

func (x *MoveResponse) GetIsLegal() bool {
	if x != nil {
		return x.IsLegal
	}
	return false
}

func (x *MoveResponse) GetNewFen() string {
	if x != nil {
		return x.NewFen
	}
	return ""
}

func (x *MoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_chess_proto protoreflect.FileDescriptor

const file_proto_chess_proto_rawDesc = "" +
	"\n" +
	"\x11proto/chess.proto\x12\x05chess\"3\n" +
	"\vMoveRequest\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12\x12\n" +
	"\x04move\x18\x02 \x01(\tR\x04move\"X\n" +
	"\fMoveResponse\x12\x19\n" +
	"\bis_legal\x18\x01 \x01(\bR\aisLegal\x12\x17\n" +
	"\anew_fen\x18\x02 \x01(\tR\x06newFen\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2F\n" +
	"\vChessEngine\x127\n" +
	"\fValidateMove\x12\x12.chess.MoveRequest\x1a\x13.chess.MoveResponseBDZBgithub.com/stanislavorlov/chess-game/backend/engineapp/proto;chessb\x06proto3"

var (
	file_proto_chess_proto_rawDescOnce sync.Once
	file_proto_chess_proto_rawDescData []byte
)

func file_proto_chess_proto_rawDescGZIP() []byte {
	file_proto_chess_proto_rawDescOnce.Do(func() {
		file_proto_chess_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chess_proto_rawDesc), len(file_proto_chess_proto_rawDesc)))
	})
	return file_proto_chess_proto_rawDescData
}

var file_proto_chess_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_chess_proto_goTypes = []any{
	(*MoveRequest)(nil),  // 0: chess.MoveRequest
	(*MoveResponse)(nil), // 1: chess.MoveResponse
}
var file_proto_chess_proto_depIdxs = []int32{
	0, // 0: chess.ChessEngine.ValidateMove:input_type -> chess.MoveRequest
	1, // 1: chess.ChessEngine.ValidateMove:output_type -> chess.MoveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chess_proto_init() }
func file_proto_chess_proto_init() {
	if File_proto_chess_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chess_proto_rawDesc), len(file_proto_chess_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chess_proto_goTypes,
		DependencyIndexes: file_proto_chess_proto_depIdxs,
		MessageInfos:      file_proto_chess_proto_msgTypes,
	}.Build()
	File_proto_chess_proto = out.File
	file_proto_chess_proto_goTypes = nil
	file_proto_chess_proto_depIdxs = nil
}
