// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: chessai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictedMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitboard      uint64                 `protobuf:"varint,1,opt,name=bitboard,proto3" json:"bitboard,omitempty"`                            // Bitboard representation (unsigned 64-bit integer)
	IsWhiteTurn   bool                   `protobuf:"varint,2,opt,name=is_white_turn,json=isWhiteTurn,proto3" json:"is_white_turn,omitempty"` // Whether the AI is playing white
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedMoveRequest) Reset() {
	*x = PredictedMoveRequest{}
	mi := &file_chessai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedMoveRequest) ProtoMessage() {}

func (x *PredictedMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chessai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedMoveRequest.ProtoReflect.Descriptor instead.
func (*PredictedMoveRequest) Descriptor() ([]byte, []int) {
	return file_chessai_proto_rawDescGZIP(), []int{0}
}

func (x *PredictedMoveRequest) GetBitboard() uint64 {
	if x != nil {
		return x.Bitboard
	}
	return 0
}

func (x *PredictedMoveRequest) GetIsWhiteTurn() bool {
	if x != nil {
		return x.IsWhiteTurn
	}
	return false
}

type PredictedMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UciMove       string                 `protobuf:"bytes,1,opt,name=uci_move,json=uciMove,proto3" json:"uci_move,omitempty"` // e.g. "e2e4"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedMoveResponse) Reset() {
	*x = PredictedMoveResponse{}
	mi := &file_chessai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedMoveResponse) ProtoMessage() {}

func (x *PredictedMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chessai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedMoveResponse.ProtoReflect.Descriptor instead.
func (*PredictedMoveResponse) Descriptor() ([]byte, []int) {
	return file_chessai_proto_rawDescGZIP(), []int{1}
}

func (x *PredictedMoveResponse) GetUciMove() string {
	if x != nil {
		return x.UciMove
	}
	return ""
}

var File_chessai_proto protoreflect.FileDescriptor

const file_chessai_proto_rawDesc = "" +
	"\n" +
	"\rchessai.proto\x12\achessai\"V\n" +
	"\x14PredictedMoveRequest\x12\x1a\n" +
	"\bbitboard\x18\x01 \x01(\x04R\bbitboard\x12\"\n" +
	"\ris_white_turn\x18\x02 \x01(\bR\visWhiteTurn\"2\n" +
	"\x15PredictedMoveResponse\x12\x19\n" +
	"\buci_move\x18\x01 \x01(\tR\auciMove2^\n" +
	"\tAiService\x12Q\n" +
	"\x10GetPredictedMove\x12\x1d.chessai.PredictedMoveRequest\x1a\x1e.chessai.PredictedMoveResponseB\x17Z\x15engineapp/proto;protob\x06proto3"

var (
	file_chessai_proto_rawDescOnce sync.Once
	file_chessai_proto_rawDescData []byte
)

func file_chessai_proto_rawDescGZIP() []byte {
	file_chessai_proto_rawDescOnce.Do(func() {
		file_chessai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chessai_proto_rawDesc), len(file_chessai_proto_rawDesc)))
	})
	return file_chessai_proto_rawDescData
}

var file_chessai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chessai_proto_goTypes = []any{
	(*PredictedMoveRequest)(nil),  // 0: chessai.PredictedMoveRequest
	(*PredictedMoveResponse)(nil), // 1: chessai.PredictedMoveResponse
}
var file_chessai_proto_depIdxs = []int32{
	0, // 0: chessai.AiService.GetPredictedMove:input_type -> chessai.PredictedMoveRequest
	1, // 1: chessai.AiService.GetPredictedMove:output_type -> chessai.PredictedMoveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chessai_proto_init() }
func file_chessai_proto_init() {
	if File_chessai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chessai_proto_rawDesc), len(file_chessai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chessai_proto_goTypes,
		DependencyIndexes: file_chessai_proto_depIdxs,
		MessageInfos:      file_chessai_proto_msgTypes,
	}.Build()
	File_chessai_proto = out.File
	file_chessai_proto_goTypes = nil
	file_chessai_proto_depIdxs = nil
}
