// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: gamestate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameState_GetState_FullMethodName = "/gamestate.GameState/GetState"
)

// GameStateClient is the client API for GameState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameStateClient interface {
	GetState(ctx context.Context, in *GameStateRequest, opts ...grpc.CallOption) (*GameStateResponse, error)
}

type gameStateClient struct {
	cc grpc.ClientConnInterface
}

func NewGameStateClient(cc grpc.ClientConnInterface) GameStateClient {
	return &gameStateClient{cc}
}

func (c *gameStateClient) GetState(ctx context.Context, in *GameStateRequest, opts ...grpc.CallOption) (*GameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameStateResponse)
	err := c.cc.Invoke(ctx, GameState_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameStateServer is the server API for GameState service.
// All implementations must embed UnimplementedGameStateServer
// for forward compatibility.
type GameStateServer interface {
	GetState(context.Context, *GameStateRequest) (*GameStateResponse, error)
	mustEmbedUnimplementedGameStateServer()
}

// UnimplementedGameStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameStateServer struct{}

func (UnimplementedGameStateServer) GetState(context.Context, *GameStateRequest) (*GameStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedGameStateServer) mustEmbedUnimplementedGameStateServer() {}
func (UnimplementedGameStateServer) testEmbeddedByValue()                   {}

// UnsafeGameStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameStateServer will
// result in compilation errors.
type UnsafeGameStateServer interface {
	mustEmbedUnimplementedGameStateServer()
}

func RegisterGameStateServer(s grpc.ServiceRegistrar, srv GameStateServer) {
	// If the following call panics, it indicates UnimplementedGameStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameState_ServiceDesc, srv)
}

func _GameState_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameStateServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameState_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameStateServer).GetState(ctx, req.(*GameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameState_ServiceDesc is the grpc.ServiceDesc for GameState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gamestate.GameState",
	HandlerType: (*GameStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _GameState_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamestate.proto",
}
