// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game": {
            "post": {
                "description": "creates a new chess game state in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create game state",
                "parameters": [
                    {
                        "description": "Game State",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.GameState"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.GameState"
                        }
                    },
                    "400": {
                        "description": "Failed to decode or create game",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/computer": {
            "post": {
                "description": "creates a new chess game state in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create computer game state",
                "parameters": [
                    {
                        "description": "Game State",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestComputerGame"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.GameState"
                        }
                    },
                    "400": {
                        "description": "Failed to decode or create game",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/online": {
            "post": {
                "description": "requests a new online game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create a record in the Matching queue",
                "parameters": [
                    {
                        "description": "Game State",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestOnlineGame"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.GameState"
                        }
                    },
                    "400": {
                        "description": "Failed to decode or create game",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/{gameId}": {
            "get": {
                "description": "retrieves the current state of a chess game from the database",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "gameId is required or failed to fetch game",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "returns the health status of the engineapp service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.GameFormat": {
            "type": "object",
            "properties": {
                "minutes": {
                    "type": "integer"
                },
                "moveIncrementMs": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "database.GamePlayers": {
            "type": "object",
            "properties": {
                "darkPlayerId": {
                    "type": "string"
                },
                "lightPlayerId": {
                    "type": "string"
                }
            }
        },
        "database.GameResult": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "winner": {
                    "type": "string"
                }
            }
        },
        "database.GameState": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/database.GameFormat"
                },
                "id": {
                    "type": "string"
                },
                "players": {
                    "$ref": "#/definitions/database.GamePlayers"
                },
                "result": {
                    "$ref": "#/definitions/database.GameResult"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "health.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.RequestComputerGame": {
            "type": "object",
            "properties": {
                "baseTime": {
                    "description": "Starting time in seconds",
                    "type": "integer"
                },
                "color": {
                    "description": "white, black, random",
                    "type": "string"
                },
                "difficulty": {
                    "description": "engine strength level",
                    "type": "string"
                },
                "format": {
                    "description": "blitz, rapid, classical, bullet",
                    "type": "string"
                },
                "increment": {
                    "description": "Increment in seconds per move",
                    "type": "integer"
                },
                "startingFen": {
                    "description": "Optional: custom starting position",
                    "type": "string"
                }
            }
        },
        "models.RequestOnlineGame": {
            "type": "object",
            "properties": {
                "baseTime": {
                    "description": "Starting time in seconds",
                    "type": "integer"
                },
                "colorPreference": {
                    "description": "white, black, random",
                    "type": "string"
                },
                "culture": {
                    "description": "en, es, fr, de, etc.",
                    "type": "string"
                },
                "format": {
                    "description": "blitz, rapid, classical, bullet",
                    "type": "string"
                },
                "increment": {
                    "description": "Increment in seconds per move",
                    "type": "integer"
                },
                "opponentId": {
                    "description": "Optional: direct challenge",
                    "type": "string"
                },
                "rated": {
                    "description": "Is the game affecting ELO?",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EngineApp API",
	Description:      "This is the Chess Engine App service responsible for game logic and AI moves.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
