basePath: /
definitions:
  database.GameFormat:
    properties:
      minutes:
        type: integer
      moveIncrementMs:
        type: integer
      name:
        type: string
    type: object
  database.GamePlayers:
    properties:
      darkPlayerId:
        type: string
      lightPlayerId:
        type: string
    type: object
  database.GameResult:
    properties:
      reason:
        type: string
      winner:
        type: string
    type: object
  database.GameState:
    properties:
      createdAt:
        type: string
      finishedAt:
        type: string
      format:
        $ref: '#/definitions/database.GameFormat'
      id:
        type: string
      players:
        $ref: '#/definitions/database.GamePlayers'
      result:
        $ref: '#/definitions/database.GameResult'
      startedAt:
        type: string
      status:
        type: string
    type: object
  health.HealthResponse:
    properties:
      service:
        type: string
      status:
        type: string
    type: object
  models.RequestComputerGame:
    properties:
      baseTime:
        description: Starting time in seconds
        type: integer
      color:
        description: white, black, random
        type: string
      difficulty:
        description: engine strength level
        type: string
      format:
        description: blitz, rapid, classical, bullet
        type: string
      increment:
        description: Increment in seconds per move
        type: integer
      startingFen:
        description: 'Optional: custom starting position'
        type: string
    type: object
  models.RequestOnlineGame:
    properties:
      baseTime:
        description: Starting time in seconds
        type: integer
      colorPreference:
        description: white, black, random
        type: string
      culture:
        description: en, es, fr, de, etc.
        type: string
      format:
        description: blitz, rapid, classical, bullet
        type: string
      increment:
        description: Increment in seconds per move
        type: integer
      opponentId:
        description: 'Optional: direct challenge'
        type: string
      rated:
        description: Is the game affecting ELO?
        type: boolean
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is the Chess Engine App service responsible for game logic and
    AI moves.
  title: EngineApp API
  version: "1.0"
paths:
  /game:
    post:
      consumes:
      - application/json
      description: creates a new chess game state in the database
      parameters:
      - description: Game State
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/database.GameState'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.GameState'
        "400":
          description: Failed to decode or create game
          schema:
            type: string
      summary: Create game state
      tags:
      - games
  /game/{gameId}:
    get:
      description: retrieves the current state of a chess game from the database
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Game status
          schema:
            type: string
        "400":
          description: gameId is required or failed to fetch game
          schema:
            type: string
      summary: Get game state
      tags:
      - games
  /game/computer:
    post:
      consumes:
      - application/json
      description: creates a new chess game state in the database
      parameters:
      - description: Game State
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/models.RequestComputerGame'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.GameState'
        "400":
          description: Failed to decode or create game
          schema:
            type: string
      summary: Create computer game state
      tags:
      - games
  /game/online:
    post:
      consumes:
      - application/json
      description: requests a new online game
      parameters:
      - description: Game State
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/models.RequestOnlineGame'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.GameState'
        "400":
          description: Failed to decode or create game
          schema:
            type: string
      summary: Create a record in the Matching queue
      tags:
      - games
  /health/live:
    get:
      description: returns the health status of the engineapp service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      summary: Check service health
      tags:
      - health
swagger: "2.0"
