basePath: /
definitions:
  database.GameState:
    properties:
      createdAt:
        type: string
      finishedAt:
        type: string
      gameStatus:
        type: string
      id:
        type: string
      startedAt:
        type: string
    type: object
  health.HealthResponse:
    properties:
      service:
        type: string
      status:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is the Chess Engine App service responsible for game logic and
    AI moves.
  title: EngineApp API
  version: "1.0"
paths:
  /game:
    post:
      consumes:
      - application/json
      description: creates a new chess game state in the database
      parameters:
      - description: Game State
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/database.GameState'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.GameState'
        "400":
          description: Failed to decode or create game
          schema:
            type: string
      summary: Create game state
      tags:
      - games
  /game/{gameId}:
    get:
      description: retrieves the current state of a chess game from the database
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Game status
          schema:
            type: string
        "400":
          description: gameId is required or failed to fetch game
          schema:
            type: string
      summary: Get game state
      tags:
      - games
  /health/live:
    get:
      description: returns the health status of the engineapp service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      summary: Check service health
      tags:
      - health
swagger: "2.0"
