# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamestate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamestate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgamestate.proto\x12\tgamestate\"#\n\x10GameStateRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\" \n\x11GameStateResponse\x12\x0b\n\x03\x66\x65n\x18\x01 \x01(\t2R\n\tGameState\x12\x45\n\x08GetState\x12\x1b.gamestate.GameStateRequest\x1a\x1c.gamestate.GameStateResponseB\x1bZ\x19\x65ngineapp/proto;gamestateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamestate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031engineapp/proto;gamestate'
  _globals['_GAMESTATEREQUEST']._serialized_start=30
  _globals['_GAMESTATEREQUEST']._serialized_end=65
  _globals['_GAMESTATERESPONSE']._serialized_start=67
  _globals['_GAMESTATERESPONSE']._serialized_end=99
  _globals['_GAMESTATE']._serialized_start=101
  _globals['_GAMESTATE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
