basePath: /api
definitions:
  models.Stat:
    properties:
      id:
        type: string
      timestamp:
        type: string
      type:
        type: string
      value:
        type: number
    required:
    - type
    - value
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a sample server for stats collection.
  title: Stats API
  version: "1.0"
paths:
  /stats:
    get:
      description: Fetch all stats from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Stat'
            type: array
      summary: Get all stats
      tags:
      - stats
    post:
      consumes:
      - application/json
      description: Create a stat entry in the database
      parameters:
      - description: Stat Data
        in: body
        name: stat
        required: true
        schema:
          $ref: '#/definitions/models.Stat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Stat'
      summary: Create a new stat
      tags:
      - stats
swagger: "2.0"
